---
# tasks file for jenkin
- name: Add Jenkins Repository
  yum_repository:
    name: jenkins
    description: Jenkins Official Repository
    baseurl:  https://pkg.jenkins.io/redhat/jenkins.repo
    gpgcheck: yes
    gpgkey:  https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: persent

- name: Start Jenkins Service
  systemd:
    name: jenkins
    state: started

