--
# tasks file for Environment_vars
- name: Set up environment variables for Jenkins
  lineinfile:
    path: /etc/environment
    line: 'JENKINS_HOME=/var/lib/jenkins'
    state: present
    create: yes

- name: Set up environment variables for SonarQube
  lineinfile:
    path: /etc/environment
    line: 'SONARQUBE_HOME=/opt/sonarqube'
    state: present
    create: yes

