--
# tasks file for ec2_configuration
- name: Install required packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip

- name: Install AWS CLI
  become: true
  pip:
    name: awscli

- name: Configure AWS CLI with access key and secret
  become: true
  command: aws configure set {{ item.key }} {{ item.value }}
  with_items:
    - { key: aws_access_key_id, value: YOUR_ACCESS_KEY }
    - { key: aws_secret_access_key, value: YOUR_SECRET_KEY }

